[hooks]
on_new_message = "notify-send --app-name \"$CHATTERS_APP_NAME\" \"New message from $CHATTERS_SENDER_NAME\" \"$CHATTERS_MESSAGE_BODY\""

[keybinds.normal]

q = ":quit<Enter>"

J = ":next-contact<Enter>"
"<S-Down>" = ":next-contact<Enter>"

K = ":prev-contact<Enter>"
"<S-Up>" = ":prev-contact<Enter>"

j = ":next-message<Enter>"
"<Down>" = ":next-message<Enter>"

k = ":prev-message<Enter>"
"<Up>" = ":prev-message<Enter>"

i = ":mode-compose<Enter>"

g = ":select-message 0<Enter>"
G = ":select-message -1<Enter>"

I = ":compose-in-editor<Enter>"

"<Enter>" = ":send-message<Enter>"

"?" = ":keybindings<Enter>"
h = ":command-history<Enter>"

aa = ":attach-files "
ad = ":detach-files "

zt = ":align-message top<Enter>"
zb = ":align-message bottom<Enter>"

[keybinds.popup]

j = ":scroll-popup 1<Enter>"
k = ":scroll-popup -1<Enter>"
